version: "3.5"

services:
  chatgptbot:
    # image: yym68686/chatgpt:latest
    build: .
    container_name: chatgptbot

    environment:
      BOT_TOKEN: 
      GOOGLE_AI_API_KEY: 
      ADMIN_LIST: ""
      CUSTOM_MODELS: "-all,gemini-2.5-pro-preview-03-25,gemini-2.5-flash-preview-04-17"
      temperature: "0.7"
      CHAT_MODE: global
      PASS_HISTORY: 20
      PROACTIVE_AGENT_ENABLED: "True"
      PROACTIVE_AGENT_MODEL: "gemini-2.5-flash-preview-04-17"
      SYSTEMPROMPT: |-
        # 你的角色基本信息

    volumes:
      - ./user_configs:/home/user_configs
      - ./utils:/home/utils
      - ./bot.py:/home/bot.py
      - ./config.py:/home/config.py
      - ./aient:/home/aient
      - ./md2tgmd:/home/md2tgmd
    ports:
      - 80:8080